INSERT INTO server(server_name) VALUES ('안타레스');
INSERT INTO server(server_name) VALUES ('아크투르스');
INSERT INTO server(server_name) VALUES ('알데바란');
INSERT INTO server(server_name) VALUES ('루페온');
INSERT INTO server(server_name) VALUES ('이그하람');
INSERT INTO server(server_name) VALUES ('기에나');
INSERT INTO server(server_name) VALUES ('시리우스');
INSERT INTO server(server_name) VALUES ('크라테르');
INSERT INTO server(server_name) VALUES ('프로키온');